# Generated by Django 4.0.5 on 2022-06-16 06:43

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photocolect', models.ImageField(upload_to=None, verbose_name='Фото для Коллеции')),
                ('title', models.TextField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'Коллекция',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=150, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=150, verbose_name='Ответ')),
                ('pucture', models.ImageField(upload_to='', verbose_name='Фото для помощи')),
            ],
            options={
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photonews', models.ImageField(upload_to=None, verbose_name='Фотография для новостей')),
                ('zaganews', models.TextField(max_length=200, verbose_name='Заголовок')),
                ('opisanie', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Onas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaga', models.TextField(max_length=150, verbose_name='Заголовок')),
                ('opisanie', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('photo1', models.ImageField(upload_to=None)),
                ('photo2', models.ImageField(upload_to=None)),
                ('photo3', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Prem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(max_length=254, upload_to=None, verbose_name='Изображение')),
                ('zagalovok', models.TextField(max_length=150, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ugolok', models.TextField(max_length=150, verbose_name='Заголовок')),
                ('opisanie', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Публичный оферта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderpole', models.ImageField(upload_to=None, verbose_name='Фото для Слайдера')),
                ('sliderpu', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Svyaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepole', models.TextField(max_length=200, verbose_name='Имя')),
                ('numberpole', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('vremya', models.DateTimeField(auto_now=True)),
                ('callback', models.TextField(max_length=150, verbose_name='Обратный звонок')),
                ('stazvonili', models.BooleanField(default=None, verbose_name='Cтатус позвонили')),
            ],
            options={
                'verbose_name_plural': 'Обратный звонок с фронта',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('imagetovar', models.ImageField(upload_to='None/%Y/%m/%d', verbose_name='Фотографии')),
                ('nametovar', models.TextField(max_length=150, verbose_name='Название товара')),
                ('articul', models.TextField(max_length=150, verbose_name='Aртикул')),
                ('pricetovar', models.IntegerField(blank=True, verbose_name='Цена')),
                ('old_price', models.IntegerField(verbose_name='Старая Цена')),
                ('pricediscount', models.IntegerField(verbose_name='Процент скидки')),
                ('descriptiontovar', ckeditor.fields.RichTextField(verbose_name='Описание Товара')),
                ('size_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размерный ряд')),
                ('tkan', models.CharField(max_length=200, verbose_name='Состав ткани')),
                ('material', models.CharField(max_length=155, verbose_name='Материал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovars', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'Товар',
                'ordering': ('nametovar',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TovarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colortovar', colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#808080', 'gray'), ('#000080', 'navy')], default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('TovarItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar', to='shop.tovar')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='None/%Y/%m/%d', validators=[shop.models.validate_even])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_image', to='shop.tovar')),
            ],
            options={
                'verbose_name_plural': 'Фото продукта',
            },
        ),
    ]
