# Generated by Django 4.0.5 on 2022-06-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pers',
            new_name='personcart',
        ),
    ]
