# Generated by Django 4.0.5 on 2022-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svyaz',
            name='callback',
        ),
        migrations.AddField(
            model_name='tovar',
            name='poiskizbrannye',
            field=models.BooleanField(default=1, verbose_name='Избранные'),
            preserve_default=False,
        ),
    ]
