# Generated by Django 4.0.5 on 2022-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_svyaz_callback_tovar_poiskizbrannye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitemimage',
            options={'verbose_name_plural': 'Фото для продукта'},
        ),
        migrations.AlterModelOptions(
            name='tovar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tovaritem',
            options={'verbose_name_plural': 'Цвет товара'},
        ),
        migrations.AlterIndexTogether(
            name='tovar',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='articul',
            field=models.CharField(max_length=150, verbose_name='Aртикул'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='nametovar',
            field=models.CharField(max_length=150, verbose_name='Название товара'),
        ),
    ]
