# Generated by Django 4.0.5 on 2022-06-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_tovar_options_tovar_hitofsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='newtov',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
    ]
