# Generated by Django 4.0.5 on 2022-06-20 04:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_tovar_newtov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heder', models.ImageField(blank=True, null=True, upload_to='None/%Y/%m/%d', verbose_name='Логотип для Хедера')),
                ('foter', models.ImageField(blank=True, null=True, upload_to='None/%Y/%m/%d', verbose_name='Логотип для Футера')),
                ('numheder', models.IntegerField(blank=True, verbose_name='Номер в хедере')),
                ('contacts', multiselectfield.db.fields.MultiSelectField(choices=[('Number', 'Number'), ('Mail', 'Mail'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp')], max_length=10, verbose_name='Выбор из списка')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инфо о контакте')),
                ('telnum', models.IntegerField(blank=True, verbose_name='Номер')),
                ('mail', models.EmailField(max_length=100, verbose_name='Почта')),
                ('insta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграм')),
                ('tele', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм')),
                ('wats', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ватсап')),
            ],
            options={
                'verbose_name': 'Футер и Хедер',
            },
        ),
        migrations.CreateModel(
            name='Vybor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wats', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='Ватсап')),
                ('tele', models.CharField(blank=True, editable=False, max_length=30, null=True, verbose_name='Телеграм')),
                ('contacts', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('telnum', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона')),
            ],
        ),
    ]
