# Generated by Django 4.0.5 on 2022-06-20 06:12

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_footer_vybor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='quantity_inline_tovar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество в линейке'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contacts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Number', 'Number'), ('Mail', 'Mail'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp')], max_length=150, verbose_name='Выбор из списка'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='foter',
            field=models.ImageField(blank=True, default=1, upload_to='None/%Y/%m/%d', verbose_name='Логотип для Футера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='heder',
            field=models.ImageField(blank=True, default=1, upload_to='None/%Y/%m/%d', verbose_name='Логотип для Хедера'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_item_cart', colorfield.fields.ColorField(default='#FF0000', editable=False, image_field=None, max_length=18, samples=None)),
                ('size_item_cart', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размер')),
                ('price_item', models.IntegerField(blank=True, verbose_name='Цена')),
                ('oldprice_item', models.IntegerField(blank=True, verbose_name='Старая Цена')),
                ('sale_item_cart', models.IntegerField(blank=True, verbose_name='Скидка')),
                ('quantity_item', models.DecimalField(decimal_places=1, max_digits=1)),
                ('quantity_item_lines', models.IntegerField(blank=True, verbose_name='Кол-во всех линеей')),
                ('quantity_cart_lines', models.IntegerField(blank=True, verbose_name='Кол-во всех товаров в  линейках')),
                ('quantity_cart_price', models.IntegerField(blank=True, verbose_name='сумма цен всех линеек')),
                ('sale_item', models.IntegerField(blank=True, verbose_name='Старая цена - цена')),
                ('result_price', models.IntegerField(blank=True, verbose_name='Стоимость - скидка')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='shop.tovar')),
                ('product_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='shop.tovaritem')),
                ('product_item_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items_imageimagetovar', to='shop.productitemimage')),
            ],
        ),
    ]
