# Generated by Django 4.0.5 on 2022-06-21 04:47

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_tovar_quantity_inline_tovar_alter_footer_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_item_cart', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая цена до учета скидок')),
                ('quantity_item', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_item_lines', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество линеек')),
                ('quantity_cart_lines', models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во всех товаров в  линейках')),
                ('sale_item', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма всех скидок')),
                ('result_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Итого к оплате')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cust', models.IntegerField(blank=True, verbose_name='Имя')),
                ('firs_cust', models.IntegerField(blank=True, verbose_name='Фамилия')),
                ('email_customer', models.EmailField(max_length=254, verbose_name='Почта')),
                ('number_cust', models.IntegerField(blank=True, verbose_name='Номер Телефона')),
                ('country', models.CharField(max_length=200, null=True, verbose_name='Страна')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Город')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('choice_contact', multiselectfield.db.fields.MultiSelectField(choices=[('Оформлен', 'Оформлен'), ('Отменен', 'Отменен'), ('Новый', 'Новый')], default=('Новый', 'Новый'), max_length=150, verbose_name='Выбор из списка')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_item_image',
        ),
        migrations.AddField(
            model_name='tovar',
            name='colortovar',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#808080', 'gray'), ('#000080', 'navy')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity_item',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='result_price',
            field=models.IntegerField(blank=True, verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sale_item',
            field=models.IntegerField(blank=True, verbose_name='Сумма всех скидок'),
        ),
        migrations.AlterField(
            model_name='prem',
            name='icon',
            field=models.FileField(max_length=95, upload_to=None, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sliderpu',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TovarItem',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='custom_cart', to='shop.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shop.shippingaddress'),
        ),
    ]
