# Generated by Django 4.0.5 on 2022-06-21 06:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cartitem_shippingaddress_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name_cart',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='image_item',
            field=models.ImageField(blank=True, null=True, upload_to='None/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='color_item_cart',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#808080', 'gray'), ('#000080', 'navy')], default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='colortovar',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#808080', 'gray'), ('#000080', 'navy')], default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет товару'),
        ),
    ]
