# Generated by Django 4.0.5 on 2022-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_name_cart_tovar_image_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Vybor',
        ),
        migrations.AlterField(
            model_name='footer',
            name='telnum',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер'),
        ),
        migrations.DeleteModel(
            name='ProductItemImage',
        ),
    ]
