# Generated by Django 4.0.5 on 2022-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_productitemimage_product_delete_vybor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_item',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=''),
        ),
    ]
