# Generated by Django 4.0.5 on 2022-06-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cartitem_quantity_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Оформление заказа'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Футер и Хедер'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Адрес доставки'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity_item',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество Товара'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_item',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество Товара'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='firs_cust',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name_cust',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
    ]
