# Generated by Django 4.0.5 on 2022-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image_cart',
            field=models.ImageField(blank=True, upload_to='None/%Y/%m/%d', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name_cart',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
