# Generated by Django 4.0.5 on 2022-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_vybor_remove_footer_foter_remove_footer_heder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vybor',
            options={'verbose_name_plural': 'Лого и номер футера'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='color_item_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='oldprice_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity_cart_lines',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity_cart_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity_item_lines',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='result_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sale_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sale_item_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size_item_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity_inline_tovar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество в линейке'),
        ),
    ]
