# Generated by Django 4.0.5 on 2022-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_vybor_options_remove_cart_color_item_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='custom_cart', to='shop.tovar'),
        ),
    ]
