# Generated by Django 4.0.5 on 2022-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='custom_cart', to='shop.cart'),
        ),
    ]
