# Generated by Django 4.0.5 on 2022-06-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_cartitem_price_item_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity_inline_tovar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество в линейке'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_item_lines',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество всех линеек'),
        ),
    ]
