# Generated by Django 4.0.5 on 2022-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_cartitem_quantity_inline_tovar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sale_item_cart',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
    ]
