# Generated by Django 4.0.5 on 2022-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_cartitem_sale_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svyaz',
            name='namepole',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
    ]
