# Generated by Django 4.0.5 on 2022-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_svyaz_namepole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity_inline_tovar',
            field=models.IntegerField(default=1, verbose_name='К-во в линейке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_cart_lines',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='К-во всехтов в лке'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_inline_tovar',
            field=models.IntegerField(blank=True, null=True, verbose_name='К-во в линейке'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_item_lines',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кв-о всех линеек'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='quantity_inline_tovar',
            field=models.IntegerField(default=1, verbose_name='Кол-во в линейке'),
            preserve_default=False,
        ),
    ]
