# Generated by Django 4.0.5 on 2022-06-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_cart_quantity_inline_tovar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size_item',
        ),
    ]
