# Generated by Django 4.0.5 on 2022-06-24 04:45

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_cartitem_size_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colortovar', colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#00FF00', 'lime'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#808080', 'gray'), ('#000080', 'navy')], default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('TovarItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar', to='shop.tovar')),
            ],
            options={
                'verbose_name_plural': 'Цвет товара',
            },
        ),
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='None/%Y/%m/%d', validators=[shop.models.validate_even])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_image', to='shop.tovar')),
            ],
            options={
                'verbose_name_plural': 'Фото для продукта',
            },
        ),
    ]
