# Generated by Django 4.0.5 on 2022-06-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_productitemimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity_cart_lines',
        ),
    ]
